services:
  ingest:
    image: ghcr.io/offsetmods538/monkeymetrics-server:latest
    container_name: ingest
    restart: unless-stopped
    networks:
      - traefik-proxy
      - telemetry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telemetry-ingest.rule=Host(`analytics.offsetmonkey538.top`) && PathPrefix(`/ingest`)"
      - "traefik.http.services.telemetry-ingest.loadbalancer.server.port=6969"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - "--storage.tsdb.retention.size=16GB"
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus:rw
    networks:
      - telemetry

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - traefik-proxy
      - telemetry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telemetry-grafana.rule=Host(`analytics.offsetmonkey538.top`)"
      - "traefik.http.services.telemetry-grafana.loadbalancer.server.port=3000"

  grafana-renderer:
    image: grafana/grafana-image-renderer
    container_name: grafana-renderer
    restart: unless-stopped
    networks:
      - telemetry

  nginx:
    image: nginx:latest
    container_name: grafana-renderer-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik-proxy
      - telemetry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telemetry-grafana-renderer.rule=Host(`analytics.offsetmonkey538.top`) && PathPrefix(`/render`)"
      - "traefik.http.services.telemetry-grafana-renderer.loadbalancer.server.port=80"


networks:
    telemetry:
    traefik-proxy:
      external: true
